# Generated by Django 3.2 on 2021-05-29 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_received',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_msg', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
                ('sender_msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
